"""Generate docs/MAP.md, and fail when the repository stops matching it.

The map exists so that "where do I look for X" is answerable without reading the tree, and so a
file cannot sit in the repository unexplained. It is generated rather than written: each entry's
purpose comes from the file's own docstring or leading comment, so the map cannot drift into
describing code that has since changed.

Two checks, and deliberately only two -- this is a map, not a style police:

  1. every tracked path falls under a documented area (a new undocumented file fails);
  2. every repository path referenced by a tracked doc, script or paper actually exists
     (a dangling reference fails).

Usage:
    python tools/repo_map.py            # rewrite docs/MAP.md
    python tools/repo_map.py --check    # verify, write nothing (run by `make check`)
"""

from __future__ import annotations

import argparse
import ast
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MAP = ROOT / "docs" / "MAP.md"

# (glob, area title, one-line description, collapse). Order matters: the first match wins, so
# narrow globs precede broad ones. `collapse` folds an area into a single counted row -- used for
# bulk result cells and figure sets, where per-file rows would be noise rather than a map.
AREAS: list[tuple[str, str, str, bool]] = [
    ("*.md",                    "Root",       "Repository front matter and agent instructions.", False),
    ("*.tex",                   "Root",       "Generated LaTeX tables (see their generator) and the paper source.", False),
    ("*.pdf",                   "Root",       "Built paper. Regenerate with `make`.", False),
    ("Makefile",                "Root",       "Every command this repository supports. Start here.", False),
    ("run_bench.sh",            "Root",       "Full-pipeline entry point.", False),
    ("*",                       "Root",       "Packaging, licence, citation metadata.", False),

    ("docs/*",                  "docs/",      "Project state and reference. `.claude/STATE_FILES` names the ones read at session start.", False),

    ("lm_adapt_bench/tests/**", "Package tests", "Pytest suite for the pipeline; run by `make check`.", True),
    ("lm_adapt_bench/contamination/*", "Package: contamination", "The six-stage audit (near-dup, split leakage, Min-K++, CoDeC, DCQ, MAD calibration).", False),
    ("lm_adapt_bench/**",       "Package",    "The pipeline itself: config -> data -> sweep -> adapt -> evaluate -> report.", False),

    ("tools/gcp_*.sh",          "tools/ run drivers", "Stage data to GCS and run one analysis on GCE, one model at a time.", False),
    ("tools/analyze_*.py",      "tools/ analysis",    "Turn finished result cells into a committed JSON artifact. All support `--check`.", False),
    ("tools/verify_*.py",       "tools/ gates",       "Reproducibility gates: assert the paper against the artifacts.", False),
    ("tools/check_*.py",        "tools/ gates",       "Structural gates over the repository and its artifacts.", False),
    ("tools/repo_map.py",       "tools/ gates",       "This file.", False),
    ("tools/plot_*.py",         "tools/ figures",     "Figure generators. Every figure in the paper is produced by one of these.", False),
    ("tools/**",                "tools/ helpers",     "One-off analysis, data preparation and reporting scripts run against finished results.", False),

    ("eval/*",                  "eval/",      "Standalone MMLU-Pro / HellaSwag / GSM8K harness (separate from the BPB pipeline).", False),
    ("slurm/*",                 "slurm/",     "Leonardo batch scripts. Never run these on the login node.", False),

    ("results/legacy_*/**",     "results/ superseded", "Superseded runs, kept because the paper reports them alongside the current answer.", True),
    ("results/_council/*",      "results/ review",     "Adjudicated council and review documents cited by the state files.", False),
    ("results/*/**",            "results/ cells",      "Raw result cells and harness logs, per experiment.", True),
    ("results/*",               "results/ artifacts",  "Committed analysis artifacts. Each is written by one `tools/analyze_*.py` and asserted by a gate.", False),

    ("figures/extra/*",         "figures/extra", "Exploratory correlation plots, not used by the paper.", True),
    ("figures/*",               "figures/",   "Paper and slide figures. Generated by `tools/plot_*.py`.", False),
    ("slides/*",                "slides/",    "Team-talk deck and speaker script. `make slides`.", False),
    ("data/**",                 "data/",      "Dataset manifests and fingerprint indexes -- provenance, not corpora.", False),
    ("benchmarks/*",            "benchmarks/", "Published leaderboard submissions.", False),
    ("reports/**",              "reports/",   "Rendered HTML/PDF report of the superseded 11-model sweep.", True),
    (".github/**",              ".github/",   "CI workflow and issue/PR templates.", False),
    (".gitignore",              "Root",       "Allowlist-style: `results/` is ignored, then evidence is un-ignored file by file.", False),
]

# A referenced path is only checked when it starts with one of these, so shell variables
# (`$WORK/...`), remote URIs and illustrative placeholders are not mistaken for repository files.
CHECKED_ROOTS = ("benchmarks/", "data/", "docs/", "eval/", "figures/", "lm_adapt_bench/",
                 "reports/", "results/", "slides/", "slurm/", "tools/")
# Paths that are deliberately illustrative rather than real.
PLACEHOLDERS = ("results/my-run/", "results/<", "docs/<")
# Documentation and the paper only. Scripts legitimately name paths that exist only while a job
# runs -- slurm/phase_run.sh echoes `results/report.pdf`, which the run itself writes -- so
# checking them would report working code as broken. A dangling path in a *document* misleads a
# reader, which is what this gate is for.
SOURCE_SUFFIXES = (".md", ".tex")
# The filename is matched GREEDILY so the extension binds to the LAST dot: non-greedy stops at
# the first known suffix, which turned `report.html.j2` into a reference to `report.html`.
REF = re.compile(r"(?<![\w/.$])((?:[\w.\-]+/)+[\w.\-]+\.(?:jsonl\.gz|sbatch|jsonl|yaml|json|toml|html|tsv|txt|cff|pdf|png|csv|tex|yml|sh|py|md|gz|j2))(?![\w])")


def tracked() -> list[str]:
    out = subprocess.run(["git", "-C", str(ROOT), "ls-files"], capture_output=True, text=True, check=True)
    return sorted(p for p in out.stdout.splitlines() if p)


def purpose(path: str) -> str:
    """The file's own one-line self-description, or "" when it has none."""
    full = ROOT / path
    try:
        text = full.read_text(encoding="utf-8", errors="ignore")
    except (OSError, UnicodeDecodeError):
        return ""
    if path.endswith(".py"):
        try:
            doc = ast.get_docstring(ast.parse(text))
        except SyntaxError:
            return ""
        return doc.strip().splitlines()[0].rstrip(".") if doc else ""
    if path.endswith((".sh", ".sbatch")):
        for line in text.splitlines()[:12]:
            s = line.strip()
            if s.startswith("#") and not s.startswith("#!") and not s.startswith("#SBATCH"):
                body = s.lstrip("# ").strip()
                if len(body) > 12:
                    return body.rstrip(".")
        return ""
    if path.endswith(".md"):
        for line in text.splitlines():
            s = line.strip()
            if s and not s.startswith("#"):
                return re.sub(r"[*`\[\]]|\(\S+\)", "", s).strip().rstrip(".")[:110]
        return ""
    return ""


def _matcher(glob: str) -> re.Pattern[str]:
    """Compile a glob where `*` stops at a path separator and `**` crosses them.

    `fnmatch` is unusable here: its `*` matches `/`, so the root-level `*.md` pattern would also
    claim `docs/PLAN.md` and the first area would swallow the whole tree.
    """
    out, i = [], 0
    while i < len(glob):
        if glob.startswith("**", i):
            out.append(".*")
            i += 2
        elif glob[i] == "*":
            out.append("[^/]*")
            i += 1
        elif glob[i] == "?":
            out.append("[^/]")
            i += 1
        else:
            out.append(re.escape(glob[i]))
            i += 1
    return re.compile("^" + "".join(out) + "$")


_COMPILED = [(_matcher(g), t, d, c) for g, t, d, c in AREAS]


def area_of(path: str) -> tuple[str, str, bool] | None:
    for pattern, title, desc, collapse in _COMPILED:
        if pattern.match(path):
            return title, desc, collapse
    return None


def build() -> tuple[str, list[str]]:
    """Return the rendered map and the list of tracked paths no area claims."""
    groups: dict[str, tuple[str, bool, list[str]]] = {}
    order: list[str] = []
    unmapped: list[str] = []
    for path in tracked():
        hit = area_of(path)
        if hit is None:
            unmapped.append(path)
            continue
        title, desc, collapse = hit
        if title not in groups:
            groups[title] = (desc, collapse, [])
            order.append(title)
        groups[title][2].append(path)

    lines = [
        "# Repository map",
        "",
        "**Generated by `tools/repo_map.py` — do not hand-edit.** Regenerate with",
        "`python tools/repo_map.py`; `make check` fails if a tracked file is missing from this map or",
        "if a path referenced anywhere in the repository does not exist.",
        "",
        "Purposes below are each file's own docstring or leading comment, so this map cannot describe",
        "code that has since changed. Bulk result cells and figure sets are counted, not listed.",
        "",
    ]
    for title in order:
        desc, collapse, paths = groups[title]
        lines += [f"## {title}", "", desc, ""]
        if collapse:
            lines += [f"- `{_common(paths)}` — {len(paths)} files.", ""]
            continue
        lines += ["| path | what it is |", "|---|---|"]
        for p in paths:
            lines.append(f"| `{p}` | {purpose(p) or '—'} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n", unmapped


def _common(paths: list[str]) -> str:
    parts = paths[0].split("/")
    while len(parts) > 1:
        prefix = "/".join(parts)
        if all(p.startswith(prefix + "/") or p == prefix for p in paths):
            return prefix + "/"
        parts.pop()
    return parts[0] + "/"


def dangling() -> list[str]:
    """Repository paths referenced by a tracked source file but absent from disk."""
    bad: dict[str, set[str]] = {}
    for path in tracked():
        if not path.endswith(SOURCE_SUFFIXES) and Path(path).name != "Makefile":
            continue
        try:
            text = (ROOT / path).read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        for ref in REF.findall(text):
            if not ref.startswith(CHECKED_ROOTS) or ref.startswith(PLACEHOLDERS):
                continue
            if (ROOT / ref).exists():
                continue
            bad.setdefault(ref, set()).add(path)
    return [f"{ref}  (referenced by {', '.join(sorted(srcs))})" for ref, srcs in sorted(bad.items())]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="verify only; write nothing")
    args = ap.parse_args()

    rendered, unmapped = build()
    missing = dangling()

    if not args.check:
        MAP.write_text(rendered, encoding="utf-8")
        print(f"wrote {MAP.relative_to(ROOT)} ({len(rendered.splitlines())} lines)")

    problems = 0
    if unmapped:
        problems += len(unmapped)
        print(f"UNMAPPED: {len(unmapped)} tracked files match no area in tools/repo_map.py:", file=sys.stderr)
        for p in unmapped[:40]:
            print(f"  {p}", file=sys.stderr)
    if missing:
        problems += len(missing)
        print(f"DANGLING: {len(missing)} referenced paths do not exist:", file=sys.stderr)
        for m in missing:
            print(f"  {m}", file=sys.stderr)
    # Staleness warns, it does not fail: a map one line out of date is not a reason to block a
    # release, and a gate that fires on cosmetic drift trains people to ignore it. An unexplained
    # file or a broken reference does fail, because both mean something is actually lost.
    if args.check and MAP.exists() and MAP.read_text(encoding="utf-8") != rendered:
        print("NOTE: docs/MAP.md is out of date; refresh it with `make map`", file=sys.stderr)

    if problems:
        sys.exit(1)
    print("repo map: OK (%d tracked files, all mapped, no dangling references)" % len(tracked()))


if __name__ == "__main__":
    main()
